version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: monitoring_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: monitoring_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring-net

volumes:
  postgres_data:

networks:
  monitoring-net:
    driver: bridge
