spring:
  application:
    name: device-monitoring

  # PostgreSQL database
  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

# Picture maximum file sizes
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

# Email connection
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# JWT
jwt:
  secret: ${JWT_SECRET}
  #expiration: 3600000 # milliseconds (1000 * 60 * 60) 1 hour
  expiration: 60000  # 1 minute
  #refresh-expiration: 604800000 # milliseconds (1000 * 60 * 60 * 24 * 7) 7 days
  refresh-expiration: 300000 # 5 minutes

# Error messages
server:
  forward-headers-strategy: native
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

app:
  pictures:
    upload-dir: uploads/pictures
    default-filename: default.png
  security:
    admin-email: ${APP_ADMIN_EMAIL}
    admin-password: ${APP_ADMIN_PASSWORD}
    bcrypt-rounds: 12
  default-server-url: http://localhost:8080

# Background tasks
jobrunr:
  background-job-server:
    enabled: true
  job-scheduler:
    enabled: true
  dashboard:
    enabled: true
    username: ${APP_ADMIN_EMAIL} # bad solution, but provides some security
    password: ${APP_ADMIN_PASSWORD} # bad solution, but provides some security
  database:
    type: postgres
    skip-create: false
    table-prefix: jobrunr_


